title: <p align="center"> Vinay Singh </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/ux-vinayofficial/">LinkedIn</a> |
  <a href="https://github.com/vinayofficial">GitHub</a>
  <br>   
    I am a 7+ years experienced UI/UX Designer and Developer working in a North Americal software MNC. <br>
    I am also persuing my MS in AI ML degree from upgrad and this page is the part of one of its course module. 
  <br>
  </p>



theme: jekyll-theme-minimal