title: Vinay Singh Shekhawat
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ux-vinayofficial/">LinkedIn</a> |
  <a href="https://github.com/vinayofficial">GitHub</a>
 
  <br>  
I am a 7+ years experienced and passionate UI/UX designer and developer. <br>
Currently, I am working as an UX Engineer in a North America based software comapny. Along with this I am also 
persuing MSc in AI ML from Upgrad and this portfolio is part of that course module.
  <br>
  </p>

theme: jekyll-theme-minimal
